### PR TITLE
add code formatter consistent with the CI check

### PR DESCRIPTION
**Pull request by dgoffredo**
These changes introduce scripts in `scripts/` for formatting the C++ source code.

Ubuntu versions more recent than 20.04 don't have a package for `clang-format-6.0`, and newer versions of clang-format format the code differently, even with the same settings.

Solutions considered:
- Let Circle CI format for me.
- Reformat the code using a more recent clang-format and modify the CI to use that.
- Use an older Ubuntu.
- Add a package source that contains `clang-format-6.0` without introducing conflicts.
- Build `clang-format-6.0` from source and keep it in my pocket.
- __Add a utility script to the repository that uses `clang-format-6.0` if available, but falls back to a docker image.__

The new `scripts/format.sh` uses the new `scripts/clang-format-6.0.sh` to format all of the C++ code.

### CODE REVIEW

**Comment by cgilmour** [comment]
Just a brief discussion on some of the considered solutions:

> Let Circle CI format for me.

I'm not a fan of the CI making code changes - it'd mean the code being pushed by the developer is different from the code that is validated by the CI.

> Reformat the code using a more recent clang-format and modify the CI to use that.

I'm OK with this, as a once-every-year-or-two event.
The reason `clang-format-6.0` was chosen is simply it was the newest available at the time.
If there's a common version between ubuntu 18.04, 20.04 and 21.xx, that'd be a reasonable choice.
That version could be from ubuntu repositories, or LLVM ones.

> Use an older Ubuntu.

Not recommended, even though it's an easy and convenient trap to get stuck in.
It can also restrict other users or contributors.

> Add a package source that contains clang-format-6.0 without introducing conflicts.

I suspect this isn't worth the effort to develop, publish and maintain. Future changes may cause conflicts.

> Build clang-format-6.0 from source and keep it in my pocket.

That solves it for a single person, but not a team or external contributor :-)

> Add a utility script to the repository that uses clang-format-6.0 if available, but falls back to a docker image.

This works, but let's also decide if we want to stick with clang-format-6.0

I did a quick pass with `clang-format-12`, and it doesn't change a lot. A few headers get reordered, different line breaks on some methods, and some additional whitespace. So it'd be easy to OK an update and reformat.
That could be as part of this PR or a followup one. Which would you prefer?

**Comment by dgoffredo** [comment]
These changes now depend on a new build image for CI: https://github.com/DataDog/docker-library/pull/71

I got rid of the Docker wrapper and instead moved everything to `clang-format-9`, including reformatting all of our code.

`clang-format-9` is available in bionic and newer: https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=clang-format-9&searchon=names

We can use an even newer version when we next upgrade our build toolchain. That can be separate.

Once that `docker-library` PR is merged and we've pushed the new image to Docker Hub, I can poke this PR again and it should go through.

**Comment by dgoffredo** [comment]
This is now ready for review.

**Review by cgilmour — APPROVED** [review]
Consider running shellcheck on the script and fixing the things it reports (not essential, just something I usually do).
I typically wouldn't use exec to invoke the formatter, but in this case it really doesn't matter.

**Pull request merged**
