### PR TITLE
Update container connections for compiled in and dynamic loading examples

### PR DESCRIPTION
**Pull request by wantsui**
When building the current compiled in example, it will lead to this error about traces being refused:

```
Error sending traces to agent: Couldn't connect to server
Failed to connect to localhost port 8126: Connection refused
```

I am making this change to correct this so traces can be sent to the Datadog Agent container (defined as `dd-agent` in the `docker-compose.yml`).

I have updated both the dynamic loading and compiled-in examples so that they both use `localhost` in the code but **DD_AGENT_HOST** in the Docker Compose file.

With this update, this is the expected output of the start up logs:

Compiled-In Example:

```
info: DATADOG TRACER CONFIGURATION - {"agent_url":"http://dd-agent:8126","analytics_enabled":false,"analytics_sample_rate":null,"date":"2021-12-14T20:28:53+0000","enabled":true,"env":"","lang":"cpp","lang_version":"201402","report_hostname":false,"sampling_rules":"[{\"sample_rate\": 1.0}]","service":"compiled-in example","version":"v1.3.1"}
```

Dynamic Loading:
```
info: DATADOG TRACER CONFIGURATION - {"agent_url":"http://dd-agent:8126","analytics_enabled":false,"analytics_sample_rate":null,"date":"2021-12-14T20:36:14+0000","enabled":true,"env":"","lang":"cpp","lang_version":"201402","report_hostname":false,"sampling_rules":"[{\"sample_rate\": 1.0}]","service":"dynamic-load example","version":"v1.3.1"}
```

### CODE REVIEW

**Comment by cgilmour** [comment]
Thanks @wantsui
I think it'll behave better if `DD_AGENT_HOST=dd-agent` is added to the docker-compose.yaml
It overrides whatever the code says, so if people compile this locally, it'll use localhost, and when run under docker-compose it'll use `dd-agent`.
That would be for both compiled-in and dynamic-loading examples.

**Comment by wantsui** [comment]
Thanks for the suggestion @cgilmour ! I'll make this change next week and update this PR!

**Comment by wantsui** [comment]
@cgilmour - I just updated the PR description with the changes that you suggested! It works when I test out the examples! As a result, I changed the title to reflect that I'm changing the dynamic loading example too.

**Review by dgoffredo — APPROVED** [review]
Looks good to me. Thanks for the contribution.

**Comment by dgoffredo** [comment]
It's complaining about the lack of signature on two out of your three commits. Might be simplest to squash your commits into a single, signed commit using `git rebase -i HEAD~3` (but take it with a grain of salt, I haven't done that before).

**Comment by wantsui** [comment]
@dgoffredo - Thanks, I'll look into this!

**Pull request merged**
