### PR TITLE
numberic -> numeric

### PR DESCRIPTION
**Pull request by dgoffredo**
I was reading through this code and saw this.  Let me know if such pull requests are a waste of time.

### CODE REVIEW

**Review by cgilmour — APPROVED** [review]
Thanks!

**Comment by cgilmour** [comment]
Thanks for spotting this. I'll check into the CI flaking on that nginx integration test.

**Comment by dgoffredo** [comment]
Cool! Yes, I was going to look into that sometime this month.  The nginx integration test failed for a different reason when I ran it locally (nonexistent github release, as opposed to the `apt` error we see here).  Will create an issue if I don't just figure it out.

**Comment by cgilmour** [comment]
I'm testing a fix for this that uses a different base image - the CI needs unblocking 😄 
I was able to test this specific one locally with `circleci local execute --job=integration_test_nginx`, but some other jobs fail because of limitations when running the local executor.

**Pull request merged**
