### PR TITLE
Add support for setting trace analytics via environment variables.

### PR DESCRIPTION
**Pull request by cgilmour**
This PR makes it possible to set the trace analytics metric on traces via an environment variable.
Users of this tracer are generally not directly writing C++ code, but using it indirectly via another application (eg: nginx, envoy, istio).
Under those circumstances, the most practical way of controlling a feature like this is via environment variables.

The variables used are:
- `DD_TRACE_ANALYTICS_ENABLED`: can be `true` (rate=1.0), `false`(rate=0.0) or unset (no rate)
- `DD_GLOBAL_ANALYTICS_SAMPLE_RATE`: a valid value between 0.0 and 1.0 inclusive.

### CODE REVIEW

**Comment by alanjcastonguay** [comment]
I'd like to get this working for the Ingress Nginx controller.

**Comment by cgilmour** [comment]
Made some changes to this implementation so that the metric is added to only the local-root span, after a trace is completed and had not been set directly.

This required some refactoring (cleanup) of the `hostname` tag, which also gets applied on local-root spans when finishing.

Tests have been added that execute the behavior via mocks (unit) and by setting the environment variable, creating new tracers and generating spans (integration).
The tests needed an update to the framework (catch2) to support a new macro that was added recently and needed for these tests.

**Comment by cgilmour** [comment]
@alanjcastonguay from testing this before shipping our release, it's not as easy as hoped.

I'd expected it to be simple - just add the variables to the ingress-controller deployment.
However, nginx "clears" the environment before launching things, and needs to be told to pass through certain environment variables.
http://nginx.org/en/docs/ngx_core_module.html#env

A short term hack would be users providing a custom nginx template.
But it'd be nice to not have that burden, and have the right settings in the default nginx template.

**Comment by cgilmour** [comment]
@alanjcastonguay I've submitted kubernetes/ingress-nginx#4371 to update to 1.0.1 so this should be in their next release. To make it work, it requires two things:
- setting env vars with values in the nginx-ingress-controller deployment, eg:
```
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              value: "test"
            - name: DD_TRACE_ANALYTICS_ENABLED
              value: "true"
```
- setting the `main-snippet` in the configmap to pass those values through to nginx, eg:
```
  enable-opentracing: "true"
  datadog-collector-host: $HOST_IP
  main-snippet: |
    env DD_ENV;
    env DD_TRACE_ANALYTICS_ENABLED;
```

I suppose they could be set directly in `main-snippet` instead of needing two changes.
Not sure which is better.

**Comment by alanjcastonguay** [comment]
The template is already tweakable based on the tracer being enabled. Maybe go code in the Ingress-nginx controller should _always_ set `env DD_ENV` and `env DD_TRACE_ANALYTICS_ENABLED` when the datadog tracer is enabled. Does having those `env` directives present _without_ the corresponding environment variables set in the deployment's pod's container spec have any downsides?

**Pull request merged**
