### PR TITLE
Update nlohmann/json

### PR DESCRIPTION
**Pull request by keith**
This fixes warnings produced by gcc on arm64 machines. This was pulled from the latest release https://github.com/nlohmann/json/releases/tag/v3.11.2

### CODE REVIEW

**Review by dgoffredo — CHANGES_REQUESTED** [review]
Major version upgrade, eh?

If it works, it works.

Please update the [Makefile](https://github.com/keith/dd-opentracing-cpp/blob/035d860566f57dd45ae17d32056da792a5047418/3rd_party/include/catch2/Makefile) in that `include/` directory so that running `make` in there downloads the new header and its license file.

**Comment by keith** [comment]
Added a Makefile for this dependency, since there wasn't one before.

**Comment by dgoffredo** [comment]
Oh, I confused the JSON library with the unit testing library, whoops.

Better this way, anyway, thanks.

**Review by dgoffredo — APPROVED** [review]
lgtm_stamp_by_nushe4ka_d5w539d-fullview

**Pull request merged**
