### PR TITLE
Fix mixed log using string concat

### PR DESCRIPTION
**Pull request by aureplop**
(Should) fix https://github.com/DataDog/dd-opentracing-cpp/issues/195.

I did not test it yet this version where we had the issues but it would be nice to check that before merging it, unless reviewers of this are already confident it will do the trick to fix the issue mentioned above.

Concatenation with "+" may not be the most performant thing but anyway this default logging function is very rarely used. I only saw the log in #195 using this format.

Also, are we ok that the log message will still be flushed to `stderr` correctly, even if it's not using `std::endl`?

Finally, I'm not sure to understand why the "build" step of CI is failing, but it also fails on other recent PR :thinking:

### CODE REVIEW

**Comment by cgilmour** [comment]
Thanks @aureplop ! Are you able to build the plugin and test it?

I'll do a separate PR to clear up the CI issues.

**Comment by aureplop** [comment]
> Are you able to build the plugin and test it?

I will give it a try on Friday. Stay tuned :drum:

**Comment by aureplop** [comment]
And so I succeed to test it locally. And this is working as expected :tada: 

With current master, using a config with `worker_processes 4`, I was reproducing the behavior described in #195 with the startup logs as expected. It only happens from time to time so I was running some `nginx -s reload` and I had some log formatting issues maybe 1 over 5 times.

On the branch on this PR, with the same setup, I did not get any issues even with a hundred of reloads.

I believe an (integration) test could be added, but it may be a bit boilerplate due to randomness (we could run the reload and check 100 times to mitigate) and it needs a change to the test config (have multiple worker_processes, currently it uses the default value of `1`). Not sure this is actually worth it.

Do you need something more from me to merge this PR @cgilmour? Thanks!

**Comment by cgilmour** [comment]
Right, it's hard to be certain if this resolves the problem or just makes it less likely to occur.
I don't think additional tests are needed, and for the most part, it's a cosmetic issue.
A future change will probably only make this message get written when a debug flag or environment variable is set.

Thanks for performing the test to confirm it resolved the issue in your case!

**Review by cgilmour — APPROVED** [review]
Looks good and seems to resolve the reported problem!

**Comment by cgilmour** [comment]
Merged, thanks @aureplop 
Is there urgency for a release that contains this change?

**Comment by aureplop** [comment]
Thanks! No emergency to release, we are using a env var to disable the startup logs causing parsing issues and this is good enough for now ;)

**Pull request merged**
